name: my-GitHubAction-Basics 

on:
  push:
    branches: 
      - master

jobs: 
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run : echo "Heello World from testing job"
      
 
  my_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run : echo "Heello World from deploy job"
